image: node:20

stages:
  - build
  - generate_pdf
  - deploy

variables:
  S3_ENDPOINT: "https://s3.lacaleche.cc"
  S3_BUCKET: "malallai"
  PDF_FILENAME: "Malo_Allain_CV"

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store

before_script:
  - corepack enable
  - corepack prepare pnpm@latest --activate
  - pnpm config set store-dir .pnpm-store

build:
  stage: build
  script:
    - pnpm install --frozen-lockfile
    - pnpm run build
  artifacts:
    paths:
      - dist/
      - node_modules/

generate_pdf:
  stage: generate_pdf
  image: mcr.microsoft.com/playwright:v1.40.0-jammy
  script:
    - corepack enable
    - corepack prepare pnpm@latest --activate
    - pnpm install --frozen-lockfile
    - pnpm exec playwright install chromium
    - pnpm run generate:pdf
  artifacts:
    paths:
      - $PDF_FILENAME.pdf

deploy_s3:
  stage: deploy
  image: amazon/aws-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - aws configure set aws_access_key_id $S3_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $S3_SECRET_ACCESS_KEY
    - aws configure set default.region fr-par
    - aws --endpoint-url $S3_ENDPOINT s3 cp $PDF_FILENAME.pdf s3://$S3_BUCKET/cv/$PDF_FILENAME-$CI_COMMIT_TAG.pdf
    - aws --endpoint-url $S3_ENDPOINT s3 cp $PDF_FILENAME.pdf s3://$S3_BUCKET/cv/$PDF_FILENAME-latest.pdf
